### PR TITLE
Bump public_suffix version

### PR DESCRIPTION
**Pull request by harlow**
How do we feel about getting `public_suffix` Gem up to `1.5.1` and doing a semver bump to `4.5.0`.

From this commit it looks like latest version of `public_suffix` will require > Ruby 2.0
https://github.com/blatyo/page_rankr/commit/2bb0e8397ba744e340e058f5b7ce06999ee31570

### CODE REVIEW

**Comment by harlow** [comment]
Looks like there are a few issues on CI. Not sure if its due to VCR; may need to update specs and avoid using FakeWeb.

**Comment by blatyo** [comment]
Yea, I'll merge and release if you get it passing. It's fine if you replace `fakeweb` with `webmock`.

**Comment by harlow** [comment]
Seems there are some nondeterministic failures in the test suite. I'm able to replicate a failure locally once out of every 6-10 runs. The rest of the time the suite passes.

**Comment by blatyo** [comment]
I suspect an issue with the threading. It may only be an issue in tests and may have something to do with `vcr` or `fakeweb` from doing something that's not thread safe.

**Comment by blatyo** [comment]
Use 4.6.0, which fixes this

**Comment by harlow** [comment]
thanks @blatyo

**Pull request merged**
